server:
  port: 3000
aws:
  access-key: "${ACCESS_KEY_AWS}"
  secret-key: "${SECRET_KEY_AWS}"
  region: "${AWS_REGION:us-east-1}"
spring:
  servlet:
    multipart.max-file-size: "${MAX_SIZE_FILE:1}MB"
    multipart.max-request-size: "${MAX_FILE_SIZE:1}MB"
  kafka:
    bootstrap-servers: "${KAFKA_SERVER:192.168.0.244:9092}"
    topics:
      bucket-topic: "${KAFKA_BUCKET_TOPIC:bucket.topic}"
      object-topic: "${KAFKA_OBJECT_TOPIC:object.topic}"
